apiVersion: v1
kind: Service
metadata:
  name: mytestservice-entrypoint
  namespace: pkube
spec:
  type: NodePort
  selector:
    app: mytestservice1
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002