apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytestservice
  namespace: pkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mytestservice1
  template:
    metadata:
      labels:
        app: mytestservice1
    spec:
      containers:
      - name: mytestservice2
        image: ptat004/mytestservice:latest
        # env:
        # - name: ASPNETCORE_URLS
        #   value: "http://*:80"
        # - name: Instance__Id
        #   value: "123"



# minikube service mydockservice-entrypoint -n mydock
# kubectl delete deployment mydockservice -n mydock
# kubectl delete service mydockservice-entrypoint -n mydock