name: docker-kube-package-test
on: [push]

jobs:
  run_tests:
    name: Publish docker image
    runs-on: ubuntu-latest
    steps:     

    - name: checkout-repo
      uses: actions/checkout@v2
      with:
        clean: 'true'

    - name: publish-docker-image
      uses: docker/build-push-action@v1
      with:
        username: "pirahawk"
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: pirahawk/dockerkubetest/mysampleservice
        tags: ${{github.run_number}},latest